using System;
using System.Data.SqlClient;
using System.IO;
using NUnit.Framework;
using SchemaZen.Library;
using SchemaZen.Library.Models;

namespace SchemaZen.Tests
{
    [TestFixture]
    class CommentTester {
        private Database _db { get; set; }
        private string _comment { get; set; }

        [TestFixtureSetUp]
        public void SetUp() {
            _db = new Database("TestScriptTableType");
            _db.Connection = ConfigHelper.TestDB.Replace("database=TESTDB", "database=" + _db.Name);
            _db.ExecCreate(true);
            _comment = String.Format(
                @"//----------------------------------------------------------------------------
             // <auto-generated>
             //     This file was generated by schemazen.
             //     Date: {0}
             //
             //     Changes to this file may cause incorrect behavior and will be lost if
             //     the code is regenerated.
             // </auto-generated>
             //----------------------------------------------------------------------------",
                DateTime.Today.ToString("MM-dd-yyyy"));

            DBHelper.ExecSql(_db.Connection, TestStrings.SetupTable0Script);
            DBHelper.ExecSql(_db.Connection, TestStrings.SetupTable1Script);
            DBHelper.ExecSql(_db.Connection, TestStrings.SetupTableTypeScript);
            DBHelper.ExecSql(_db.Connection, TestStrings.SetupFKScript);
            DBHelper.ExecSql(_db.Connection, TestStrings.SetupFuncScript);
            DBHelper.ExecSql(_db.Connection, TestStrings.SetupProcScript);
            DBHelper.ExecSql(_db.Connection, TestStrings.SetupRoleScript);
            DBHelper.ExecSql(_db.Connection, TestStrings.SetupTrigScript);
            DBHelper.ExecSql(_db.Connection, TestStrings.SetupUserScript);
            DBHelper.ExecSql(_db.Connection, TestStrings.SetupViewScript);
        }

        [Test]
        public void TestFilesContainComment()
        {
            _db.Dir = _db.Name;
            _db.Load();
            _db.ScriptToDir();

            Assert.IsTrue(ValidateFirstLineIncludesComment(_db.Name +
                "\\table_types\\" + TestStrings.TableTypeFileName, _comment));
            Assert.IsTrue(ValidateFirstLineIncludesComment(_db.Name +
                "\\foreign_keys\\" + TestStrings.TestForeignKeyFileName, _comment));
            Assert.IsTrue(ValidateFirstLineIncludesComment(_db.Name +
                "\\functions\\" + TestStrings.TestFunctionFileName, _comment));
            Assert.IsTrue(ValidateFirstLineIncludesComment(_db.Name +
                "\\procedures\\" + TestStrings.TestProcedureFileName, _comment));
            Assert.IsTrue(ValidateFirstLineIncludesComment(_db.Name +
                "\\roles\\" + TestStrings.TestRoleFileName, _comment));
            Assert.IsTrue(ValidateFirstLineIncludesComment(_db.Name +
                "\\triggers\\" + TestStrings.TestTrigFileName, _comment));
            Assert.IsTrue(ValidateFirstLineIncludesComment(_db.Name +
                "\\tables\\" + TestStrings.TestTable0FileName, _comment));
            Assert.IsTrue(ValidateFirstLineIncludesComment(_db.Name +
                "\\users\\" + TestStrings.TestUserFileName, _comment));
            Assert.IsTrue(ValidateFirstLineIncludesComment(_db.Name +
                "\\views\\" + TestStrings.TestViewFileName, _comment));
            Assert.IsTrue(ValidateFirstLineIncludesComment(_db.Name + 
                "\\" + TestStrings.PropsFileName, _comment));
            Assert.IsTrue(ValidateFirstLineIncludesComment(_db.Name + 
                "\\" + TestStrings.SchemasFileName, _comment));
        }

        [TearDown]
        public void TearDown() {
            DropDb(_db.Name);
        }

        private void DropDb(string dbName) {
            DBHelper.ExecSql("ALTER DATABASE " + dbName + " SET SINGLE_USER WITH ROLLBACK IMMEDIATE", "");
            DBHelper.ExecSql("drop database " + dbName, "");
        }

        private void ClearPool(string dbName) {
            using (var cn = new SqlConnection(_db.Connection))
            {
                SqlConnection.ClearPool(cn);
            }
        }

        bool ValidateFirstLineIncludesComment(string filePath, string matchingStr) {
            string firstLine = File.ReadAllLines(filePath)[0];
            return matchingStr.Contains(firstLine);
        }
    }
}
